# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.

# Example IP addressses used in this file:
# 22.22.22.22 - Target staging server's IP address
# 33.33.33.33 - Second worker node in this 2-server setup
# 55.55.55.55 - This IP address is both the VPN server the server used as a bastion / jump host
# 66.66.66.66 - This IP address is the address of a backup server

all:
  vars:
    # This configuration variable blocks all access to the server, including SSH, except from the IP addresses specified below.
    # This should always be set when configuring a production server if there is no other firewall in front of the server.
    # SSH and other services should never be exposed to the public internet.
    only_allow_access_from_addresses:
      - 164.90.213.144
    enable_backups: true
    periodic_restore_from_backup: false
    users:
      - name: riku
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWIF63S4f3z9wQMvWibmvl7MPuJ6EVrkP0HuvgNhcs/4DZYMcR/GRBvV4ldOSYMlBevIXycgGzNDxKJgENUuwIWanjBu7uVAHyD6+cIRD1h63qq7Cjv/2HYTfBDKOrKzPOhA6zWvKO0ZGWsjRXk5LWMCbKOkvKJCxOpj/NVBxeE4FTK5YADYPV3OSsmBtqTHrVLm2sMmShU/2hMYYswWkobidjX65+nK/X+3C+yJbHwiydVvn+QCrFlFfCLPWKe8rUpOxyxofPqWVQh6CHhHfT8okaOc9sOE8Qeip9ljo84DftJh3Xm3ynOdWK1hH2BvRvxNadWqcE1qECbkg4tx2x riku.rouvila@gmail.com
        state: present
        sudoer: true

docker-manager-first:
  hosts:
    opencrvs-countryconfig-production-01:
      ansible_host: '161.35.193.11'
      data_label: data1
      ansible_ssh_common_args: '-J jump@164.90.213.144 -o StrictHostKeyChecking=no'

# We recommend you add 2-4 workers for a scaled production deployment
# This should depend on the size of your country and the number of end users.
docker-workers:
  hosts:
    opencrvs-countryconfig-production-02:
      ansible_host: '164.90.236.207'
      data_label: data2
      ansible_ssh_common_args: '-J jump@164.90.213.144 -o StrictHostKeyChecking=no'

backups:
  hosts:
    qa:
      ansible_host: '164.90.179.82'
