# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.

all:
  vars:
    # This configuration variable blocks all access to the server, including SSH, except from the IP addresses specified below.
    # This should always be set when configuring a production server if there is no other firewall in front of the server.
    # SSH and other services should never be exposed to the public internet.
    only_allow_access_from_addresses:
      - 164.90.213.144
    enable_backups: false
    periodic_restore_from_backup: true
    users:
      - name: riku
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWIF63S4f3z9wQMvWibmvl7MPuJ6EVrkP0HuvgNhcs/4DZYMcR/GRBvV4ldOSYMlBevIXycgGzNDxKJgENUuwIWanjBu7uVAHyD6+cIRD1h63qq7Cjv/2HYTfBDKOrKzPOhA6zWvKO0ZGWsjRXk5LWMCbKOkvKJCxOpj/NVBxeE4FTK5YADYPV3OSsmBtqTHrVLm2sMmShU/2hMYYswWkobidjX65+nK/X+3C+yJbHwiydVvn+QCrFlFfCLPWKe8rUpOxyxofPqWVQh6CHhHfT8okaOc9sOE8Qeip9ljo84DftJh3Xm3ynOdWK1hH2BvRvxNadWqcE1qECbkg4tx2x riku.rouvila@gmail.com
        state: present
        sudoer: true

docker-manager-first:
  hosts:
    opencrvs-countryconfig-staging:
      ansible_host: '161.35.206.222'
      data_label: data1
      ansible_ssh_common_args: '-J jump@164.90.213.144 -o StrictHostKeyChecking=no'

# This staging servers is configured to only use one server
docker-workers: {}

# For staging server to be able to restore from backups, it needs to have access to the backup server.
# if you do not intend to set up automatic sync from the backup server, you can remove this section.
backups:
  hosts:
    opencrvs-countryconfig-backup:
      ansible_host: '164.90.179.82' # set this to be the IP address of your backup server
